version: '3'
services:
  nodeapp:
    image: khronic79/node-tasks
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    networks:
      - my_network
    restart: always
  postgres:
    build: ./db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - my_network
    restart: always
networks:
  my_network:
    driver: bridge